---
- name: Install Minikube
  hosts: localhost
  become: true
  gather_facts: yes

  tasks:
    - name: Install the necessary packages
      ansible.builtin.apt:
        name:
          - curl
        state: present
    
    - name: Download Minikube
      ansible.builtin.get_url:
        url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
        dest: "/usr/local/bin/minikube"
        mode: '0755'
    
    # - name: Install Kubectl
    #   ansible.builtin.apt:
    #     name:
    #       - kubectl
    #     state: present
    #   when: ansible_distribution == 'Ubuntu'
    
    # - name: Install Kubectl by Downloading from Google
    #   ansible.builtin.get_url:
    #     url: "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    #     dest: "/usr/local/bin/kubectl"
    #     mode: '0755'

    - name: Start Minikube
      ansible.builtin.command:
        minikube start --force # using force to make it run the docker driver without root privileges
    
    - name: Enable Metrics Server for minikube dashboard
      ansible.builtin.command:
        minikube addons enable metrics-server